title: JLAC's homepage

description: My portfolio, containing some of my personal projects and blog posts. More to come!

#remote_theme: pages-themes/minimal@v0.2.0
theme: minima

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

minima:
  skin: dark
titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

minima:
  nav_pages:
    - README.md
    - project-ecobike/intro.md
    - about/contact-us.md

params:
  defaultTheme: dark

author:
  name: José Luis Aguilar Charfén
  email: "aguilarch.joseluis@gmail.com"
