title: JLAC's homepage

<img src='assets/images/JLAC.JPEG'>
description: My portfolio, containing some of my personal projects and blog posts. More to come!

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
