title: JLAC's Portfolio

description: My portfolio, containing some of my personal projects and blog posts. More to come!

#remote_theme: pages-themes/minimal@v0.2.0
theme: minima
markdown: kramdown
usemathjax: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

header_pages:
  - README.md
  - "project-ecobike/intro.md"
  - "about/contact-us.md"

social_links:
  - { platform: github, user_url: "https://github.com/JLAC11" }
  - {
      platform: linkedin,
      user_url: "https://www.linkedin.com/in/josé-luis-aguilar-146b94194/",
    }

minima:
  skin: dark

author: José Luis Aguilar Charfén
name: José Luis Aguilar Charfén
email: "aguilarch.joseluis@gmail.com"
